Repository fora22/CodingTest, pull requests merged in 2020-10, with the labels that each got.

#6 Fora22/feature/coding test/3_1/PR
  fora22/CodingTest/main.cpp
Labels: Pull Request

#11 3-2 큰수의 법칙 예제 완료(Python, Java)
  JSY8869/CHAPTER 3/Completion/CodingTest3-2.py
  JSY8869/CHAPTER 3/Completion/CodingTest3_2_Java.java
  JSY8869/CHAPTER 3/Completion/CodingTest3_2_Java_Review.java
  JSY8869/CHAPTER 3/Completion/CodingTest3_2_Review.py
  JSY8869/CHAPTER 3/Completion/README_3-2.MD
Labels: Pull Request, Question, Refactoring, Review

#7 3-1 거스름돈 예제 완료(Python, Java)
  JSY8869/CHAPTER 3/Completion/CodingTest3-1.py
  JSY8869/CHAPTER 3/Completion/CodingTest3-1_review.py
  JSY8869/CHAPTER 3/Completion/CodingTest3_1_java.java
  JSY8869/CHAPTER 3/README.md
Labels: Pull Request, Question, Review

#14 Jsy8869/feature/coding test/3 1
  JSY8869/CHAPTER 3/Completion/CodingTest3-1.py
  JSY8869/CHAPTER 3/Completion/CodingTest3-1_review.py
  JSY8869/CHAPTER 3/Completion/CodingTest3_1_java.java
  JSY8869/CHAPTER 3/README.md
Labels: Pull Request

#15 Jsy8869/feature/coding test/3 2
  JSY8869/CHAPTER 3/Completion/CodingTest3-2.py
  JSY8869/CHAPTER 3/Completion/CodingTest3_2_Java.java
  JSY8869/CHAPTER 3/Completion/CodingTest3_2_Java_Review.java
  JSY8869/CHAPTER 3/Completion/CodingTest3_2_Review.py
  JSY8869/CHAPTER 3/Completion/README_3-2.MD
Labels: Pull Request
