Repository fora22/CodingTest, pull requests merged in 2020-12, with the labels that each got.

#38 Add README.md: development environment, build, run, test, analysis, d…
  jongfeel/KnightOfKingdom/.gitattributes
  jongfeel/KnightOfKingdom/.gitignore
  jongfeel/KnightOfKingdom/README.md
  jongfeel/KnightOfKingdom/app/build.gradle.kts
  jongfeel/KnightOfKingdom/app/src/main/java/KnightOfKingdom/App.java
  jongfeel/KnightOfKingdom/app/src/test/java/KnightOfKingdom/AppTest.java
  jongfeel/KnightOfKingdom/gradle/wrapper/gradle-wrapper.jar
  jongfeel/KnightOfKingdom/gradle/wrapper/gradle-wrapper.properties
  jongfeel/KnightOfKingdom/gradlew
  jongfeel/KnightOfKingdom/gradlew.bat
  jongfeel/KnightOfKingdom/images/chessboard_knightmovecase.jpg
  jongfeel/KnightOfKingdom/images/gradle_version.jpg
  jongfeel/KnightOfKingdom/images/java_version.jpg
  jongfeel/KnightOfKingdom/images/testcase_result.jpg
  jongfeel/KnightOfKingdom/settings.gradle.kts
Labels: Discussion, Pull Request, Review

#48 Fora22/feature/coding test/4 3
  fora22/CodingTest/UnitTest/.gitignore
  fora22/CodingTest/UnitTest/UnitTest.cpp
  fora22/CodingTest/VS/main.cpp
Labels: Pull Request, Review

#55 Jsy8869/feature/coding test/5 3
  JSY8869/CHAPTER 5/실전 5-3/CodingTest5_3_N_DFS.java
  JSY8869/CHAPTER 5/실전 5-3/README.MD
Labels: Pull Request, Question, Review
