Repository fora22/CodingTest, pull requests merged in 2020-11, with the labels that each got.

#20 3-4 1이 될 때까지 완료!
  JSY8869/CHAPTER 3/3-4/CodingTest3_4.java
  JSY8869/CHAPTER 3/3-4/CodingTest3_4_review.java
  JSY8869/CHAPTER 3/3-4/README.md
Labels: Bug, Pull Request, Question, Review

#22 refactoring (변수명 가독성 좋게 고침)
  fora22/DataStructure/Stack/foraStack_Linked_List/foraStackLinkedList.cpp
  fora22/DataStructure/Stack/foraStack_Linked_List/foraStackLinkedList.h
  fora22/DataStructure/Stack/foraStack_Linked_List/foraStackLinkedListStructure.cpp
  fora22/DataStructure/Stack/foraStack_Linked_List/foraStackLinkedListStructure.h
Labels: Pull Request, Refactoring, Review

#26 Queue Linked List - Node class, Queue class
  fora22/DataStructure/_DataStructure/foraNode.cpp
  fora22/DataStructure/_DataStructure/foraNode.h
  fora22/DataStructure/_DataStructure/foraQueue.cpp
  fora22/DataStructure/_DataStructure/foraQueue.h
Labels: Pull Request, Review

#32 4_1번 문제 해결
  fora22/CodingTest/input.txt
  fora22/CodingTest/main.cpp
Labels: Discussion, Pull Request, Question, Review
